# Generated by Django 6.1.1 on 2026-09-19 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Boys Hostel 1', max_length=100)),
                ('code', models.CharField(help_text='e.g. BH-1, GH-1', max_length=20, unique=True)),
                ('category', models.CharField(choices=[('boys', 'Boys Hostel'), ('girls', 'Girls Hostel')], default='boys', max_length=10)),
                ('latitude', models.FloatField(default=11.0253)),
                ('longitude', models.FloatField(default=77.0268)),
                ('floor_count', models.PositiveIntegerField(default=5)),
                ('capacity', models.PositiveIntegerField(default=400)),
                ('description', models.TextField(blank=True)),
                ('warden_name', models.CharField(default='Hostel Warden', max_length=100)),
                ('warden_contact', models.CharField(default='+91 422 2574071 (CIT Ext 204)', max_length=50)),
                ('security_contact', models.CharField(default='+91 422 2574072 (CIT Security)', max_length=50)),
                ('medical_contact', models.CharField(default='+91 422 2574075 (CIT Health Centre)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='HostelAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('INFO', 'Notice / Information'), ('WARNING', 'Important Update'), ('URGENT', 'Urgent / Emergency')], default='INFO', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Whether visible to public campus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(blank=True, help_text='Null for all hostels', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='hostel.hostel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Block A, Block B', max_length=50)),
                ('floor_count', models.PositiveIntegerField(default=4)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='hostel.hostel')),
            ],
            options={
                'ordering': ['hostel', 'name'],
                'unique_together': {('hostel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HostelComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('WATER', 'Drinking Water / RO Filter'), ('ELECTRICITY', 'Power / Light / Fan'), ('WIFI', 'Campus Wi-Fi / LAN'), ('ROOM', 'Room Furniture & Bed'), ('BATHROOM', 'Washroom & Plumbing'), ('CLEANING', 'Housekeeping & Hygiene'), ('SECURITY', 'Hostel Security / Biometric'), ('OTHER', 'Other Hostel Issues')], default='ELECTRICITY', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('VERIFIED', 'Verified'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='REPORTED', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='hostel.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_complaints', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(default='Hostel Common Room', max_length=100)),
                ('organizer', models.CharField(default='Hostel Committee', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hostel.hostel')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='HostelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('UTILITY', 'Essential Utilities'), ('ACADEMIC', 'Study & Research'), ('RECREATION', 'Recreation & Wellness'), ('SAFETY', 'Safety & Health')], default='UTILITY', max_length=20)),
                ('icon', models.CharField(default='✨', max_length=10)),
                ('status', models.CharField(default='Operational', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='hostel.hostel')),
            ],
            options={
                'ordering': ['hostel', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HostelMaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('item', models.CharField(help_text='e.g. Ceiling Fan, Light Fixture, Door Latch, Water Tap', max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Routine'), ('MEDIUM', 'Standard'), ('HIGH', 'High Priority'), ('EMERGENCY', 'Emergency')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Submitted'), ('IN_PROGRESS', 'Technician Assigned'), ('COMPLETED', 'Completed')], default='REPORTED', max_length=20)),
                ('technician_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='hostel.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelMessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(help_text='Monday, Tuesday, etc.', max_length=20)),
                ('breakfast', models.TextField(help_text='Idli, Sambar, Chutney, Tea/Coffee')),
                ('lunch', models.TextField(help_text='Rice, Sambar, Rasam, Kootu, Curd')),
                ('snacks', models.TextField(help_text='Sundal, Tea / Coffee')),
                ('dinner', models.TextField(help_text='Chapathi, Dal, Mixed Rice, Milk')),
                ('timing_info', models.CharField(default='Breakfast: 7:30-9:00 | Lunch: 12:30-2:00 | Dinner: 7:30-9:00', max_length=100)),
                ('special_notes', models.CharField(blank=True, max_length=255)),
                ('hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mess_menus', to='hostel.hostel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='e.g. B-101, G-204', max_length=20)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single Occupancy'), ('DOUBLE', 'Double Sharing'), ('TRIPLE', 'Triple Sharing'), ('QUAD', 'Four Sharing')], default='DOUBLE', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('occupied', models.PositiveIntegerField(default=2)),
                ('is_available', models.BooleanField(default=False)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostelblock')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
            ],
            options={
                'ordering': ['hostel', 'room_number'],
                'unique_together': {('hostel', 'room_number')},
            },
        ),
    ]
