# Generated by Django 6.1.1 on 2026-09-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Campus Main Gate North', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='traffic_uploads/')),
                ('total_vehicles', models.PositiveIntegerField(default=0)),
                ('car_count', models.PositiveIntegerField(default=0)),
                ('motorcycle_count', models.PositiveIntegerField(default=0)),
                ('bus_count', models.PositiveIntegerField(default=0)),
                ('truck_count', models.PositiveIntegerField(default=0)),
                ('congestion_level', models.CharField(choices=[('CLEAR', 'Free Flow (Clear)'), ('MODERATE', 'Moderate Traffic'), ('HEAVY', 'Heavy Traffic'), ('CONGESTED', 'Campus Gate Bottleneck / Congested')], default='CLEAR', max_length=30)),
                ('confidence', models.FloatField(default=0.88)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
