# Generated by Django 6.1.1 on 2026-09-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('REMEDIAL_CLASS', 'Remedial Session'), ('FACULTY_MENTORING', 'Faculty 1-on-1 Mentoring'), ('ASSIGNMENT_SUPPORT', 'Assignment Extension / Lab Support'), ('ATTENDANCE_WARNING', 'Attendance Warning Notice'), ('PEER_TUTORING', 'Peer Tutor Assignment')], default='FACULTY_MENTORING', max_length=40)),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Action'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Completed / Resolved')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk (Healthy Progress)'), ('MEDIUM', 'Moderate Risk (Attention Needed)'), ('HIGH', 'High Academic Risk (Critical Intervention)')], default='LOW', max_length=20)),
                ('risk_score', models.FloatField(default=15.0, help_text='Estimated failure/dropout risk % (0-100)')),
                ('confidence', models.FloatField(default=0.88)),
                ('model_name', models.CharField(default='RandomForest-Ensemble-v1', max_length=100)),
                ('contributing_factors_json', models.TextField(default='[]', help_text='JSON list of top explainable factors')),
                ('recommended_action', models.TextField(default='Regular coursework progression.')),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., CS501, AI402', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('credits', models.PositiveIntegerField(default=3)),
                ('semester', models.PositiveIntegerField(default=5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('semester', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_percentage', models.FloatField(default=85.0)),
                ('internal_marks', models.FloatField(default=75.0, help_text='Out of 100')),
                ('grade', models.CharField(default='B+', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyPerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('attendance_rate', models.FloatField(help_text='Weekly attendance % (0-100)')),
                ('quiz_score', models.FloatField(help_text='Weekly quiz score (0-100)')),
                ('assignment_score', models.FloatField(help_text='Weekly assignment score (0-100)')),
                ('lms_activity_hours', models.FloatField(default=4.0)),
            ],
            options={
                'ordering': ['student', 'week_number'],
            },
        ),
    ]
