# Generated by Django 6.1.1 on 2026-09-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('departments', '0001_initial'),
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicintervention',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='academicintervention',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='students.student'),
        ),
        migrations.AddField(
            model_name='academicriskassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='students.student'),
        ),
        migrations.AddField(
            model_name='academicintervention',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicriskassessment'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departments.department'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.course'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.courseoffering'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='weeklyperformancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_records', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course_offering')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyperformancerecord',
            unique_together={('student', 'week_number')},
        ),
    ]
