# Generated by Django 6.1.1 on 2026-09-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='e.g. PKG-NORTH, PKG-AUDITORIUM', max_length=30, unique=True)),
                ('total_slots', models.PositiveIntegerField(default=60)),
                ('latitude', models.FloatField(default=12.972)),
                ('longitude', models.FloatField(default=77.595)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=20)),
                ('slot_type', models.CharField(choices=[('CAR', 'Standard Car'), ('MOTORCYCLE', 'Two-Wheeler'), ('EV_CHARGING', 'Electric Vehicle Charging'), ('ACCESSIBLE', 'Accessible / Handicap')], default='CAR', max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['lot', 'slot_number'],
                'unique_together': {('lot', 'slot_number')},
            },
        ),
    ]
