# Generated by Django 6.1.1 on 2026-09-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='e.g. CANTEEN-MAIN, CAFE-SOUTH', max_length=30, unique=True)),
                ('location_name', models.CharField(default='Central Dining Hall', max_length=100)),
                ('seating_capacity', models.PositiveIntegerField(default=350)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch Thali / Meals'), ('SNACKS', 'Evening Snacks & Tea'), ('DINNER', 'Dinner')], default='LUNCH', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='canteen.canteen')),
            ],
        ),
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SNACKS', 'Snacks'), ('DINNER', 'Dinner')], default='LUNCH', max_length=30)),
                ('meals_prepared', models.PositiveIntegerField(default=300)),
                ('meals_sold', models.PositiveIntegerField(default=285)),
                ('leftover_waste_kg', models.FloatField(default=6.5)),
                ('is_event_day', models.BooleanField(default=False)),
                ('weather_condition', models.CharField(default='Clear', max_length=50)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_records', to='canteen.canteen')),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
                'unique_together': {('canteen', 'date', 'meal_type')},
            },
        ),
    ]
