# Generated by Django 6.1.1 on 2026-09-11 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed complaint in natural language')),
                ('category', models.CharField(choices=[('ELECTRICAL', 'Electrical & Lighting'), ('WATER', 'Water Supply & Plumbing'), ('SANITATION', 'Sanitation & Hygiene'), ('CLASSROOM', 'Classroom Infrastructure'), ('LABORATORY', 'Laboratory Equipment'), ('TRANSPORT', 'Campus Transport & Buses'), ('HOSTEL', 'Hostel Facility'), ('CANTEEN', 'Canteen & Food Quality'), ('PARKING', 'Parking & Traffic'), ('NETWORK', 'Wi-Fi & Campus Network'), ('SECURITY', 'Campus Security'), ('ACADEMIC', 'Academic / Timetable'), ('INFRASTRUCTURE', 'General Campus Infrastructure'), ('OTHER', 'Other Issues')], default='INFRASTRUCTURE', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent / Critical')], default='MEDIUM', max_length=20)),
                ('target_department', models.CharField(default='Maintenance', max_length=100)),
                ('location_extracted', models.CharField(blank=True, help_text='AI-extracted building/room location', max_length=150)),
                ('confidence', models.FloatField(default=0.85)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted (AI Triaged)'), ('ASSIGNED', 'Assigned to Staff'), ('IN_PROGRESS', 'Work in Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Closed / Inapplicable')], default='SUBMITTED', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('sla_hours', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaints.complaint')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
