# Generated by Django 6.1.1 on 2026-09-11 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Anonymized ID e.g. STU2026-0042', max_length=50, unique=True)),
                ('first_name', models.CharField(default='Student', max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('program', models.CharField(default='B.Tech', max_length=50)),
                ('semester', models.PositiveIntegerField(default=5)),
                ('section', models.CharField(default='A', max_length=10)),
                ('admission_year', models.PositiveIntegerField(default=2023)),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('cgpa', models.FloatField(default=7.5)),
                ('attendance_percentage', models.FloatField(default=82.0)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills (e.g. Python, Machine Learning, React, SQL)')),
                ('interests', models.TextField(blank=True, help_text='Comma-separated interests (e.g. Robotics, NLP, Cyber Security)')),
                ('career_interests', models.TextField(blank=True, help_text='Target role (e.g. Data Scientist, Cloud Architect)')),
                ('backlog_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='departments.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
    ]
