# Generated by Django 6.1.1 on 2026-09-19 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accommodation_type',
            field=models.CharField(choices=[('hostel', 'Hostel Student'), ('day_scholar', 'Day Scholar')], default='day_scholar', help_text='Hostel Student or Day Scholar', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_students', to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_category',
            field=models.CharField(blank=True, choices=[('boys', 'Boys Hostel'), ('girls', 'Girls Hostel')], help_text='boys or girls', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.CharField(blank=True, help_text='e.g. B-204', max_length=20),
        ),
    ]
