# Generated by Django 6.1.1 on 2026-09-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_accommodation_type_student_assigned_hostel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_accommodation_configured',
            field=models.BooleanField(default=False, help_text='Whether student completed accommodation onboarding'),
        ),
    ]
