# Generated by Django 6.1.1 on 2026-09-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Route 1 - Metro Central Express', max_length=150, unique=True)),
                ('code', models.CharField(help_text='e.g. R-01', max_length=20, unique=True)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(default='Campus Main Terminal', max_length=100)),
                ('distance_km', models.FloatField(default=12.5)),
                ('estimated_duration_mins', models.PositiveIntegerField(default=35)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(help_text='e.g. KA-01-CP-1001', max_length=30, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveIntegerField(default=52)),
                ('current_passengers', models.PositiveIntegerField(default=28)),
                ('is_active', models.BooleanField(default=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='transport.busroute')),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('estimated_offset_mins', models.PositiveIntegerField(default=5)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.busroute')),
            ],
            options={
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='GPSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_kmh', models.FloatField(default=32.0)),
                ('passenger_count', models.PositiveIntegerField(default=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_records', to='transport.bus')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
