# Generated by Django 6.1.1 on 2026-09-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(help_text='e.g. TN-38-CIT-1001', max_length=30, unique=True),
        ),
    ]
