# Generated by Django 6.1.1 on 2026-09-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical & Coding'), ('CULTURAL', 'Cultural & Arts'), ('SPORTS', 'Sports & Athletics'), ('SOCIAL', 'Community & Social Service'), ('ENTREPRENEURSHIP', 'Innovation & Entrepreneurship')], default='TECHNICAL', max_length=40)),
                ('description', models.TextField()),
                ('skills_developed', models.CharField(default='Leadership, Teamwork', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_clubs', to='faculty.faculty')),
                ('student_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_clubs', to='students.student')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClubAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('competition', models.CharField(max_length=200)),
                ('position', models.CharField(default='1st Place / Winner', max_length=100)),
                ('award_date', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'General Member'), ('CORE_LEAD', 'Core Committee Lead'), ('PRESIDENT', 'Club President'), ('SECRETARY', 'Club Secretary')], default='MEMBER', max_length=30)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='students.student')),
            ],
            options={
                'unique_together': {('club', 'student')},
            },
        ),
    ]
