# Generated by Django 6.1.1 on 2026-09-11 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='e.g., BLK-A, LAB-CS1, PKG-EAST', max_length=30, unique=True)),
                ('category', models.CharField(choices=[('ACADEMIC_BLOCK', 'Academic Block'), ('DEPARTMENT', 'Department Facility'), ('LABORATORY', 'Research / Computer Lab'), ('CANTEEN', 'Canteen / Dining Hall'), ('PARKING', 'Smart Parking Zone'), ('BUS_STOP', 'Campus Bus Stop'), ('AUDITORIUM', 'Auditorium / Seminar Hall'), ('SPORTS', 'Sports Complex / Ground'), ('HOSTEL', 'Student Hostel'), ('ADMIN_BLOCK', 'Administrative Building')], default='ACADEMIC_BLOCK', max_length=40)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('floor_count', models.PositiveIntegerField(default=1)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Degrees Celsius')),
                ('humidity', models.FloatField(default=60.0)),
                ('precipitation', models.FloatField(default=0.0, help_text='mm')),
                ('weather_code', models.IntegerField(default=0)),
                ('weather_description', models.CharField(default='Clear Sky', max_length=100)),
                ('wind_speed', models.FloatField(default=10.0, help_text='km/h')),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
