# Generated by Django 6.1.1 on 2026-10-07 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('facility_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('EVENT_HALL', 'Event Hall')], max_length=50)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('has_ac', models.BooleanField(default=False)),
                ('building', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(limit_choices_to={'facility_type': 'EVENT_HALL'}, on_delete=django.db.models.deletion.CASCADE, to='common.facility')),
            ],
        ),
    ]
