# Generated by Django 6.1.1 on 2026-09-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteImagePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='waste_uploads/')),
                ('predicted_class', models.CharField(choices=[('CARDBOARD', 'Cardboard'), ('GLASS', 'Glass'), ('METAL', 'Metal'), ('PAPER', 'Paper'), ('PLASTIC', 'Plastic'), ('TRASH', 'General Trash / Non-Recyclable')], default='PLASTIC', max_length=30)),
                ('confidence', models.FloatField(default=0.89)),
                ('disposal_recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(default='Central Campus Complex', max_length=100)),
                ('date', models.DateField()),
                ('dry_waste_kg', models.FloatField(default=42.5)),
                ('wet_waste_kg', models.FloatField(default=35.0)),
                ('recyclable_kg', models.FloatField(default=28.0)),
                ('e_waste_kg', models.FloatField(default=2.5)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
