# Generated by Django 6.1.1 on 2026-09-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Block C Computer Science', max_length=150)),
                ('meter_id', models.CharField(help_text='e.g. MTR-BLK-C-01', max_length=50, unique=True)),
                ('building_name', models.CharField(max_length=100)),
                ('baseline_kwh', models.FloatField(default=45.0, help_text='Expected daytime base load (kWh)')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh_consumed', models.FloatField(help_text='kWh')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(default=28.0)),
                ('occupancy_estimate', models.PositiveIntegerField(default=120)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='energy.energymeter')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EnergyAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_score', models.FloatField(help_text='Isolation score (-1 to 0 or 0 to 100)')),
                ('kwh_observed', models.FloatField()),
                ('kwh_expected', models.FloatField()),
                ('severity', models.CharField(choices=[('MILD', 'Mild Anomaly'), ('MODERATE', 'Moderate Anomaly'), ('CRITICAL', 'Critical Waste / Power Surge')], default='MODERATE', max_length=20)),
                ('anomaly_type', models.CharField(choices=[('NIGHT_LEAK', 'Night-time Idle Waste (Equipment Left ON)'), ('POWER_SURGE', 'Sudden Electrical Power Surge'), ('HVAC_OVERLOAD', 'HVAC / Cooling Overload'), ('EQUIPMENT_FAULT', 'Suspected Machinery / UPS Fault')], default='NIGHT_LEAK', max_length=30)),
                ('explanation', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='energy.energymeter')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='energy.energyreading')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
