# Generated by Django 6.1.1 on 2026-09-11 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOCIATE_PROF', 'Associate Professor'), ('ASSISTANT_PROF', 'Assistant Professor'), ('LECTURER', 'Lecturer / Adjunct')], default='ASSISTANT_PROF', max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('cabin_location', models.CharField(blank=True, max_length=100)),
                ('office_hours', models.CharField(default='Mon-Fri 2:00 PM - 4:00 PM', max_length=100)),
                ('is_mentor', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculty',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
