# Generated by Django 6.1.1 on 2026-09-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Academic_Risk_Classifier', max_length=120, unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=30)),
                ('task', models.CharField(choices=[('CLASSIFICATION', 'Classification'), ('REGRESSION', 'Regression / Forecasting'), ('ANOMALY_DETECTION', 'Anomaly Detection'), ('NLP', 'Natural Language Processing'), ('RECOMMENDATION', 'Recommendation')], default='CLASSIFICATION', max_length=40)),
                ('algorithm', models.CharField(max_length=120)),
                ('metrics_json', models.TextField(default='{}', help_text='Real measured evaluation metrics (F1, Accuracy, MAE, R2, etc.)')),
                ('features_json', models.TextField(default='[]', help_text='List of feature names used during training')),
                ('model_path', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('VALIDATED', 'Validated'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production'), ('RETIRED', 'Retired'), ('FAILED', 'Failed')], default='PRODUCTION', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MLTrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=120)),
                ('model_version', models.CharField(max_length=30)),
                ('algorithm', models.CharField(max_length=120)),
                ('dataset_size', models.PositiveIntegerField(default=0)),
                ('train_metrics_json', models.TextField(default='{}')),
                ('test_metrics_json', models.TextField(default='{}')),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Training Successful'), ('FAILED', 'Training Failed')], default='SUCCESS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelDriftRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=120)),
                ('metric_name', models.CharField(help_text='e.g. PSI_ATTENDANCE or KL_DIVERGENCE', max_length=100)),
                ('drift_score', models.FloatField(help_text='Calculated drift statistic')),
                ('threshold', models.FloatField(default=0.25, help_text='Drift alert threshold (typically PSI > 0.25)')),
                ('is_drift_detected', models.BooleanField(default=False)),
                ('details_json', models.TextField(default='{}')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='MLPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=120)),
                ('model_version', models.CharField(max_length=30)),
                ('task', models.CharField(default='GENERAL', max_length=40)),
                ('input_summary', models.TextField(help_text='Sanitized input feature dictionary or summary (NO credentials)')),
                ('prediction', models.TextField(help_text='Serialized output prediction value or classification')),
                ('confidence', models.FloatField(blank=True, help_text='Calibrated probability if mathematically supported', null=True)),
                ('factors_json', models.TextField(default='[]', help_text='Top explainable contributing factors')),
                ('latency_ms', models.FloatField(default=0.0, help_text='Inference execution latency in milliseconds')),
                ('status', models.CharField(choices=[('SUCCESS', 'Inference Success'), ('FAILED', 'Inference Failed'), ('FALLBACK', 'Graceful Fallback')], default='SUCCESS', max_length=20)),
                ('data_mode', models.CharField(choices=[('LIVE', 'Live Campus Telemetry'), ('DEMO', 'Simulated / Benchmark Mode')], default='LIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=120)),
                ('actual_outcome', models.TextField(help_text='Ground truth recorded value (e.g. actual attendance, actual meals sold)')),
                ('error_delta', models.FloatField(blank=True, help_text='Measured error |predicted - actual|', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='analytics.mlpredictionlog')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
