# Generated by Django 6.1.1 on 2026-09-11 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('ACADEMIC_ALERT', 'Academic Risk / Intervention'), ('EVENT_REMINDER', 'Event Registration & Pass'), ('COMPLAINT_UPDATE', 'Complaint Status Triage'), ('TRANSPORT_ALERT', 'Bus Fleet & Transport Alert'), ('ENERGY_ANOMALY', 'Energy Spike / Anomaly'), ('SYSTEM', 'Campus Broadcast')], default='SYSTEM', max_length=40)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
