# Generated by Django 6.1.1 on 2026-09-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('ACADEMIC_ALERT', 'Academic Risk / Intervention'), ('EVENT_REMINDER', 'Event Registration & Pass'), ('COMPLAINT_UPDATE', 'Complaint Status Triage'), ('TRANSPORT_ALERT', 'Bus Fleet & Transport Alert'), ('ENERGY_ANOMALY', 'Energy Spike / Anomaly'), ('HOSTEL_ALERT', 'Hostel Resident Notice'), ('SYSTEM', 'Campus Broadcast')], default='SYSTEM', max_length=40),
        ),
    ]
